#!/bin/bash

DIR_PATH="$(dirname "$0")"

source $DIR_PATH/utils.sh

cos 0
cos 30
cos 60
cos 90
cos 180

a=1.23
b=3.45
sum=$(awk -v n1="$a" -v n2="$b" 'BEGIN {print (num1 + num2)}')
echo "Sum: $sum"

x=1.25
x=1.25
x=-1.25
x=-1.25
y=2.5
z=3.75
z=5
z=5
z=2
w=4

# Convert to floating-point numbers for calculations
x=$(echo "$x" | awk '{printf "%.6f", $1}')
y=$(echo "$y" | awk '{printf "%.6f", $1}')
z=$(echo "$z" | awk '{printf "%.6f", $1}')
w=$(echo "$w" | awk '{printf "%.6f", $1}')

cos $z

if awk "BEGIN {exit !($x > 0 && $z < 5)}" ; then
    echo "case 1"
    f=$(awk "BEGIN {print ($x * $x + $w)}")
    echo "f1 = $f"
elif awk "BEGIN {exit !($x > 0 && $z >= 5)}"; then
    echo "case 2"
    cosine=$(cos "$z")
    f=$(awk -v x="$x" -v y="$y" -v cosine="$cosine" 'BEGIN {print (cosine + x * y)}')
    echo "f2 = $f"
elif awk "BEGIN {exit !($x < 0 && $z > 5)}"; then
    echo "case 3"
    cosine=$(cos "$y")
    echo $cosine
    f=$(awk -v x="$x" -v w="$w" -v cosine="$cosine" 'BEGIN {print (w + x * cosine)}')
    echo "f3 = $f"
else echo "Unsupported case"
fi
