#!/bin/bash

DIR_PATH="$(dirname "$0")"

source $DIR_PATH/CONS.sh
source $DIR_PATH/utils.sh

# 1. Enter X, Y, Z, W
if [ $# -eq 4 ]; then
    x=$1
    y=$2
    z=$3
    w=$4
else
    read -p "Enter X: " x
    read -p "Enter Y: " y
    read -p "Enter Z: " z
    read -p "Enter W: " w
fi

# 2. Print X, Y, Z, W
echo "X = $x, Y = $y, Z = $z, W = $w"

# Convert to floating-point numbers for calculations
x=$(echo "$x" | awk '{printf "%.6f", $1}')
y=$(echo "$y" | awk '{printf "%.6f", $1}')
z=$(echo "$z" | awk '{printf "%.6f", $1}')
w=$(echo "$w" | awk '{printf "%.6f", $1}')

# 3. X > 0
if awk "BEGIN {exit !($x > 0)}" ; then
    # 5. Z < 5
    if awk "BEGIN {exit !($z < 5)}"; then
        # 9. F := X ** 2 + W
        f=$(awk "BEGIN {print ($x * $x + $w)}")
    else
        # 8. F := cos(Z) + X * Y
        echo "else"
        cosine=$(cos "$z")
        f=$(awk -v x="$x" -v y="$y" -v cosine="$cosine" 'BEGIN {print (cosine + x * y)}')
    fi
    # 12. Print F
    printFormat $f $GREEN
# 4. X < 0
elif awk "BEGIN {exit !($x < 0)}"; then
    # 7. Z > 5
    if awk "BEGIN {exit !($z > 5)}"; then
        # 11. F := W + X * cos(Y)
        cosine=$(cos "$y")
        f=$(awk -v x="$x" -v w="$w" -v cosine="$cosine" 'BEGIN {print (w + x * cosine)}')
        # 12. Print F
        printFormat $f $GREEN
    else
        # 9. Print Unsupported case
        printFormat "Случай не предусмотрен" $GREEN
    fi
else
    # 6. Print Unsupported case
    printFormat "Случай не предусмотрен" $GREEN
fi
